### ISSUE TITLE
Permissions error in loading Buckeye on Roquefort

### ISSUE THREAD

**Issue by james-tanner** [MontrealCorpusTools/SPADE#10]
When loading Buckeye after a corpus reset, I run into the following error when trying to parse the corpus files:

```
Parsing files...
Parsing file 1 of 255 (s1003a)...
Traceback (most recent call last):
  File "duration.py", line 89, in <module>
    common.loading(config, corpus_conf['corpus_directory'], corpus_conf['input_format'])
  File "/home/linguistics/jtanner/SPADE/Common/common.py", line 126, in loading
    c.load(parser, corpus_dir)
  File "/home/linguistics/jtanner/PolyglotDB/polyglotdb/corpus/importable.py", line 132, in load
    could_not_parse = self.load_directory(parser, path)
  File "/home/linguistics/jtanner/PolyglotDB/polyglotdb/corpus/importable.py", line 249, in load_directory
    self.add_discourse(data)
  File "/home/linguistics/jtanner/PolyglotDB/polyglotdb/corpus/importable.py", line 106, in add_discourse
    setup_audio(self, data)
  File "/home/linguistics/jtanner/PolyglotDB/polyglotdb/acoustics/io.py", line 75, in setup_audio
    add_discourse_sound_info(corpus_context, data.name, data.wav_path)
  File "/home/linguistics/jtanner/PolyglotDB/polyglotdb/acoustics/io.py", line 43, in add_discourse_sound_info
    shutil.copy(filepath, consonant_path)
  File "/home/linguistics/jtanner/miniconda3/envs/polyglot/lib/python3.6/shutil.py", line 242, in copy
    copymode(src, dst, follow_symlinks=follow_symlinks)
  File "/home/linguistics/jtanner/miniconda3/envs/polyglot/lib/python3.6/shutil.py", line 144, in copymode
    chmod_func(dst, stat.S_IMODE(st.st_mode))
PermissionError: [Errno 1] Operation not permitted: '/data/mmcauliffe/polyglot_data/spade-Buckeye/spade-Buckeye/data/audio/s1003a/consonant.wav'
```
I assume this is because of where the files are stored and/or that I don't have sudo permissions. The YAML file has the corpus directory set as `/projects/spade/repo/git/spade-Buckeye/`.

**Comment by msonderegger** [comment]
@mmcauliffe shouldn't the YAML file make the directory what James says?

Is this related to the issue that James says he still has a pull request outstanding for?

**Comment by james-tanner** [comment]
@mmcauliffe mentioned that this is related to a permissions issue that came up in prepping for a talk. Like @msonderegger said, I would have thought that it would parse the files from the `/projects/spade/repo/git/spade-Buckeye` directory - is there a reason why it pulls from `/data/mmcauliffe/` after corpus reset?

**Comment by mmcauliffe** [comment]
Changed ownership of the polyglot_data directory to spade_repo, so it might work now?

**Comment by james-tanner** [comment]
I also get permissions errors when running this on new corpora after making the appropriate .yaml:
```
Traceback (most recent call last):
  File "formant.py", line 37, in <module>
    config = CorpusConfig(corpus_name, **params)
  File "/home/linguistics/jtanner/miniconda3/envs/polyglot/lib/python3.6/site-packages/polyglotdb-0.1.18-py3.6.egg/polyglotdb/config.py", line 79, in __init__
    os.makedirs(self.base_dir, exist_ok=True)
  File "/home/linguistics/jtanner/miniconda3/envs/polyglot/lib/python3.6/os.py", line 220, in makedirs
    mkdir(name, mode)
PermissionError: [Errno 13] Permission denied: '/data/mmcauliffe/polyglot_data/spade-Hastings/spade-Hastings'
```

**Comment by james-tanner** [comment]
I still get the same permissions error when I try this.
