### ISSUE TITLE
Neobolt error exporting CSV for in sibilant analysis

### ISSUE THREAD

**Issue by james-tanner** [MontrealCorpusTools/SPADE#20]
I've been testing `sibilant.py` using the Modern RP corpus, and I get this error output, which is presumably something about how Polyglot is generating the column names, right? This currently runs fine on ICE-Can, so this might be a corpus-specific error.

```
Traceback (most recent call last):
  File "sibilant.py", line 47, in <module>
    common.sibilant_export(config, corpus_name, corpus_conf['dialect_code'], corpus_conf['speakers'])
  File "/home/linguistics/jtanner/SPADE/Common/common.py", line 392, in sibilant_export
    qr.to_csv(csv_path)
  File "/data/iscan-spade-server/src/polyglotdb/polyglotdb/query/annotations/query.py", line 402, in to_csv
    r = q.all()
  File "/data/iscan-spade-server/src/polyglotdb/polyglotdb/query/annotations/query.py", line 228, in all
    return QueryResults(self)
  File "/data/iscan-spade-server/src/polyglotdb/polyglotdb/query/annotations/results.py", line 117, in __init__
    super(QueryResults, self).__init__(query)
  File "/data/iscan-spade-server/src/polyglotdb/polyglotdb/query/base/results.py", line 19, in __init__
    self.cursors = [self.corpus.execute_cypher(query.cypher(), **query.cypher_params()).records()]
  File "/data/iscan-spade-server/src/polyglotdb/polyglotdb/corpus/base.py", line 98, in execute_cypher
    results = session.run(statement, **parameters)
  File "/home/linguistics/jtanner/miniconda3/lib/python3.6/site-packages/neo4j/__init__.py", line 496, in run
    self._connection.fetch()
  File "/home/linguistics/jtanner/miniconda3/lib/python3.6/site-packages/neobolt/direct.py", line 416, in fetch
    return self._fetch()
  File "/home/linguistics/jtanner/miniconda3/lib/python3.6/site-packages/neobolt/direct.py", line 454, in _fetch
    response.on_failure(summary_metadata or {})
  File "/home/linguistics/jtanner/miniconda3/lib/python3.6/site-packages/neobolt/direct.py", line 744, in on_failure
    raise CypherError.hydrate(**metadata)
neobolt.exceptions.CypherSyntaxError: Multiple result columns with the same name are not supported (line 31, column 186 (offset: 5281))
"    RETURN node_Speaker.name AS speaker, node_Discourse.name AS discourse, node_phone.id AS phone_id, node_phone.label AS phone_label, node_phone.begin AS begin, node_phone.end AS end, node_phone.end - node_phone.begin AS duration, node_foll_1_phone.label AS following_phone, node_prev_1_phone.label AS previous_phone, node_phone_syllable_word.label AS word, node_phone_syllable_word.id AS word_id, node_phone_syllable.stress AS syllable_stress, extract(n in node_phone_onset_in_node_phone_syllable|n.label) AS onset, extract(n in node_phone_nucleus_in_node_phone_syllable|n.label) AS nucleus, extract(n in node_phone_coda_in_node_phone_syllable|n.label) AS coda, node_phone.cog AS cog, node_phone.peak AS peak, node_phone.slope AS slope, node_phone.spread AS spread, node_Speaker.duration AS duration, node_Speaker.decade_of_birth AS decade_of_birth, node_Speaker.speaker_id AS speaker_id, node_Speaker.dialect AS dialect, node_Speaker.date_of_recording AS date_of_recording, node_Speaker.other_information AS other_information, node_Speaker.socioeconomic_class AS socioeconomic_class, node_Speaker.transcriptionalignment AS transcriptionalignment, node_Speaker.file_name AS file_name, node_Speaker.gender AS gender"
```

**Comment by mmcauliffe** [comment]
Looks like there's a column in the speaker enrichment file named "duration" which is the name of the phone duration column.  I don't know what that means for a speaker to have duration, so maybe check that out and change the name as appropriate.

**Comment by james-tanner** [comment]
I think it's supposed to be the duration of that speaker's recorded conversation? This is handled by polyglot anyway, so it's a redundant column. I'll remove it and retry.

**Comment by james-tanner** [comment]
Yep, that fixed it! I'll check the name change into the main corpus repo.
