### ISSUE TITLE
Resetting corpora with scripts causes crash

### ISSUE THREAD

**Issue by MichaelGoodale** [MontrealCorpusTools/SPADE#49]
Currently if you run a script with the reset flag, you get an error due to the corpus directory not existing. This is because it looks for the corpus *inside* the corpus, ex:
```no vowel prototypes path given, so using no prototypes
Processing...
{'graph_http_port': 7400, 'graph_bolt_port': 7402, 'acoustic_http_port': 8400, 'data_dir': '/site/proj/polyglot_data/spade-ModernRP', 'host': 'app'}
Resetting the corpus.
Traceback (most recent call last):
  File "sibilant.py", line 43, in <module>
    common.loading(config, corpus_conf['corpus_directory'], corpus_conf['input_format'])
  File "/site/proj/SPADE/Common/common.py", line 101, in loading
    with CorpusContext(config) as c:
  File "/site/proj/PolyglotDB/polyglotdb/corpus/base.py", line 152, in __enter__
    self.cache_hierarchy()
  File "/site/proj/PolyglotDB/polyglotdb/corpus/base.py", line 174, in cache_hierarchy
    with open(self.hierarchy_path, 'w', encoding='utf8') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/site/proj/polyglot_data/spade-ModernRP/spade-ModernRP/hierarchy'

```

Resetting does work however, and if you re-run the script afterwards without the `-r` flag you get the intended behaviour

**Comment by msonderegger** [comment]
Aha -- nice catch. I think @james-tanner may have run into this issue before. Could you put on your queue to fix?

**Comment by mmcauliffe** [comment]
@MichaelGoodale is this fixed by the recent commit that modifies how resetting works?

**Comment by MichaelGoodale** [comment]
Yes it is
